site_name: My Docs
site_url: https://asap-programmer.github.io/static-site-pages
site_description: A modern static site built with MkDocs and custom React theme
site_author: Ilvir Nizaev

theme:
  name: null
  custom_dir: custom_theme
  static_templates:
    - 404.html

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

nav:
  - Home: index.md
  - Features: features.md
  - Development: development.md

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
